---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: blue
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: blue
    namespace: flux-system
  git:
    push:
      branch: continuous-deployment
    commit:
      author:
        email: github-actions[bot]@users.noreply.github.com
        name: github-actions[bot]
      messageTemplate: |
        Deploying `{{ .AutomationObject }}`

        {{ range $_, $url := .Updated.Images -}}
        {{ $url }}
        {{ end -}}
