---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - namespace.yaml
  - source.yaml
  - image-policy.yaml
  - image-repository.yaml
  - image-update-automation.yaml
