---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: blue
spec:
  interval: 10m
  url: https://github.com/gitops-remote-dev/blue
  ref:
    branch: master

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blue
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: blue
    namespace: flux-system
  targetNamespace: blue
  path: ./deploy/overlays/local
  prune: true
  wait: true
  timeout: 5m
