---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - |-
    kind: Provider
    metadata:
      name: slack-error
    spec:
      channel: prod-deployment-alerts
  - |-
    kind: Provider
    metadata:
      name: slack-info
    spec:
      channel: prod-deployments
