---
apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata:
  name: https-gateway
spec:
  gatewayClassName: cilium-gateway-class
  listeners:
    - protocol: HTTPS
      port: 443
      routes:
        kind: HTTPRoute
        selector:
          matchLabels:
            gateway: https-gateway
        namespaces:
          from: "Same"
