---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: https
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTPS
      port: 443
      routes:
        kind: HTTPRoute
        selector:
          matchLabels:
            gateway: https

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: http
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTP
      port: 80
      routes:
        kind: HTTPRoute
        selector:
          matchLabels:
            gateway: http
