---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
spec:
  interval: 24h
  ref:
    branch: main
  url: http://github.com/kubernetes-sigs/gateway-api
  ignore: |
    # exclude all
    /*
    # include specific files
    !/config/crd/kustomization.yaml
    !/config/crd/standard/*
    !/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
