---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mqtt
spec:
  releaseName: mqtt
  targetNamespace: mqtt
  chart:
    spec:
      chart: zilla
      sourceRef:
        kind: HelmRepository
        name: zilla
        namespace: flux-system
      version: "^0.9.68"
  interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: mqtt-values
