# https://github.com/aklivity/zilla/blob/develop/cloud/helm-chart/src/main/helm/values.yaml
---
service:
  ports:
    - name: mqtt
      port: 1883

zilla.yaml: |
  name: MQTT

  bindings:
    north_tcp_server:
      type: tcp
      kind: server
      options:
        host: 0.0.0.0
        port: 1883
      exit: north_mqtt_server

    north_mqtt_server:
      type: mqtt
      kind: server
      exit: north_mqtt_kafka_mapping

    north_mqtt_kafka_mapping:
      type: mqtt-kafka
      kind: proxy
      options:
        topics:
          sessions: mqtt-sessions
          messages: mqtt-messages
          retained: mqtt-retained
      exit: north_kafka_cache_client

    north_kafka_cache_client:
      type: kafka
      kind: cache_client
      exit: south_kafka_cache_server

    south_kafka_cache_server:
      type: kafka
      kind: cache_server
      options:
        bootstrap:
          - mqtt-sessions
          - mqtt-messages
          - mqtt-retained
      exit: south_kafka_client

    south_kafka_client:
      type: kafka
      kind: client
      exit: south_kafka_tcp_client

    south_kafka_tcp_client:
      type: tcp
      kind: client
      options:
        host: redpanda.redpanda.svc.cluster.local
        port: 9092
      routes:
        - when:
            - cidr: 0.0.0.0/0
