---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  releaseName: grafana
  targetNamespace: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "6.58.7"
  interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: grafana-values
