---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: system-upgrade-controller
spec:
  interval: 24h
  ref:
    branch: master
  url: https://github.com/rancher/system-upgrade-controller

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller
spec:
  interval: 12h
  sourceRef:
    kind: GitRepository
    name: system-upgrade-controller
    namespace: flux-system
  targetNamespace: rancher
  path: ./
  prune: true
  wait: true
  timeout: 5m
