---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds-standard
spec:
  interval: 12h
  sourceRef:
    kind: GitRepository
    name: gateway-api
    namespace: flux-system
  path: ./config/crd
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds-experimental
spec:
  interval: 12h
  sourceRef:
    kind: GitRepository
    name: gateway-api
    namespace: flux-system
  path: ./config/crd/experimental
  prune: true
