---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - crd.yaml
  - release.yaml
configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml=values.yaml
components:
  - ../../components/configurations
