---
kubeProxyReplacement: true
k8sServiceHost: "192.168.4.53"
k8sServicePort: "6443"
gatewayAPI:
  enabled: true
loadBalancer:
  mode: dsr
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
