---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-crs
spec:
  dependsOn:
    - name: external-secrets-crds
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./secrets/overlays/develop
  prune: true
