---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-crds
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: external-secrets
    namespace: flux-system
  path: ./deploy/crds
  prune: true
