---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
configMapGenerator:
  - name: external-secrets-values
    files:
      - values.yaml=values.yaml
components:
  - ../../components/configurations
resources:
  - namespace.yaml
  - deployment-crds.yaml
  - release.yaml
  - service-account.yaml
