# gcloud iam service-accounts add-iam-policy-binding secrets-manager@kinetic-dryad-364616.iam.gserviceaccount.com \
#     --role roles/iam.workloadIdentityUser \
#     --member "serviceAccount:kinetic-dryad-364616.svc.id.goog[external-secrets/external-secrets]"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
    iam.gke.io/gcp-service-account: secrets-manager@kinetic-dryad-364616.iam.gserviceaccount.com
