---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - sealed-secret.yaml
  - release.yaml
configMapGenerator:
  - name: cloudflare-tunnel-values
    files:
      - values.yaml=values.yaml
components:
  - ../../components/configurations
patchesStrategicMerge:
- |
  kind: SealedSecret
  metadata:
    namespace: cloudflare
