---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgB8IoVjCSr+159+pByIpA3IOmisv4TwAKIUBComaQ9WVSrdwaFq4z300T/fNpJ/vVFZvOhny+rYR7tasxpfnt6d5vAr57xsFp2n/Cqa1VRgIzynjB9OlktsKEMaIVRpTR8ifjU+LOhyM7sNyKz0RgwqFwNVHQFeTlMPUQE9btv/shLDOb0dLZp4oBwyivcWdjY6CSINGPOg4Nd2RthS9BOkOQ2sueKklWYVEK73+RNDlnHBT3f1TWSK4vBq73HncVHh2HkHdwyX/jThFOT/PXAaLR7J59JWFO1kV0VZwEAZx4oLW3YMXw9R0TehuJ/iNNpx0wZgkJCguu/S0COdIvLOOL1nZ7v+4EU6baU4sKKDX8j1GDuS1F7goSDYULYa6r0fSJgml2r25RxQKce7+2DWNv54RC345RA5nJkglLMwSIGExU3vZ7O5M9Q7CqGN70Z33mhYl7Hi+ZQk025qGIK4/PkOqhpBzlcZGYic3vVOWxeQAcvJZ6B7EwdylJZ1crWlxF7t5Nc0V6lToB+INS+6+AwtOtwCSPnXGEtXYkjd9Y7k/anm5XS20P/VJYNOSGd7hV6xFlo8o6MvR1qL75TjJXdIxpfnttwzsRBY1KE76wCc2Tld5ShBlSAhN6jyCF5ATzb4SyMujYwq5iRxPCfy7Y8ft/IGMXY5LzVO0yPZLiJec9nwEJ/6haecwPWelbAxgAhXXtCGpzRTHQ3zBch2jhBR47oIrqcc4Aryf6TD7rIYtcbejOAkPNk/cQW4K7p/ZX9I6+KSDbWkdk2SHaYcCuj1rPD271xND5u7G4T0GGGtMF/Lig36JLVhr1S6AkWGx1ZsINTLz9RQjjncIin/LwsEO1P/qtLVggUp28/1BdKK9DivlDNFPEwTxKOJudXh64prX6+9x/mpGCNfuDA9UsbvaAmS5qFvxi9+
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared
      namespace: cloudflare
