---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: homebridge
spec:
  parentRefs:
    - kind: Gateway
      name: http
      namespace: kube-system
  hostnames:
    - homebridge.dudo.dev
    - homebridge.marin.dev
  rules:
    - backendRefs:
        - name: homebridge
          port: 8080
