---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: homebridge
spec:
  gateways:
    allow: FromList
    gatewayRefs:
      - name: http
  # hostnames:
  #   - dudo.dev
  rules:
    - matches:
        - path:
            type: Prefix
            value: /
      forwardTo:
        - serviceName: homebridge
          port: 8080
