apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: homebridge
  labels:
    gateway: https-gateway
spec:
  gateways:
    allow: FromList
    gatewayRefs:
    - name: https-gateway
      namespace: default
  rules:
    - matches:
      - path:
          type: Prefix
          value: /
      forwardTo:
      - serviceName: homebridge
        port: 8080
