---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
configMapGenerator:
  - name: homebridge-config
    envs:
      - .env
