---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  releaseName: node-feature-discovery
  targetNamespace: node-feature-discovery
  chart:
    spec:
      chart: node-feature-discovery
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
      version: "^0.2.1"
  interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: node-feature-discovery-values
