---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-auth
  namespace: local
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .json | toString }}"
    name: registry-auth
    creationPolicy: Owner
  data:
    - secretKey: json
      remoteRef:
        key: docker-registry-authentication
