apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcpsm
spec:
  provider:
    gcpsm:
      projectID: kinetic-dryad-364616
      auth:
        workloadIdentity:
          clusterLocation: us-west1
          clusterName: compada-dev
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
