---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-auth
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    template:
      type: Opaque
      data:
        username: dudo
        password: "{{ .token | toString }}"
    name: git-auth
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: github-authentication
