---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana-agent
spec:
  releaseName: grafana-agent
  targetNamespace: grafana
  chart:
    spec:
      chart: grafana-agent
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "^0.32.0"
  interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: grafana-agent-values
