---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-agent-operator
spec:
  releaseName: grafana-agent-operator
  targetNamespace: grafana
  chart:
    spec:
      chart: grafana-agent-operator
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "0.3.0"
  interval: 1h
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: grafana-agent-operator-values
