apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: zigbee2mqtt
  labels:
    gateway: http
spec:
  gateways:
    allow: All
  # hostnames:
  #   - dudo.dev
  rules:
    - matches:
        - path:
            type: Prefix
            value: /
      forwardTo:
        - serviceName: zigbee2mqtt
          port: 8080
