---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - deployment.yaml
  - persistent-volume-claim.yaml
  - persistent-volume.yaml
  - service.yaml
  - http-route.yaml
