---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - http-route.yaml
configMapGenerator:
  - name: zigbee2mqtt-defaults
    files:
      - configuration.yaml=configuration.yaml
  - name: zigbee2mqtt-config
    envs:
      - .env
