---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - configmap.yaml
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - http-route.yaml
