---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - persistent-volume.yaml
  - service.yaml
  - stateful-set.yaml
  - http-route.yaml
configMapGenerator:
  - name: zigbee2mqtt-config
    envs:
      - .env
