---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/on/host" # TODO: Adjust this to the desired path on your host
