---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/zigbee2mqtt
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: tp2.turingpi.com/slot
              operator: In
              values:
                - "2"
