---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../sources
  - cert-manager
  - cilium
  # - cloudflare-tunnel
  # - grafana
  - mqtt
  - node-feature-discovery
  - nvidia-device-plugin
  # - postgres # I'm not ready to install this yet. Need to work out storage. Longhorn?
  - redpanda
  - vault
