---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../sources
  - cilium
  - sealed-secrets
  - nvidia-device-plugin
  - grafana
  - cloudflare-tunnel
  - cert-manager
  - redpanda
