---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
spec:
  interval: 24h
  url: https://charts.external-secrets.io

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-secrets
spec:
  interval: 24h
  ref:
    branch: main
  url: http://github.com/external-secrets/external-secrets
