---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - cilium.yaml
  - cloudflare.yaml
  - grafana.yaml
  - jetstack.yaml
  # - metrics-server.yaml # This is included with k0s
  - node-feature-discovery.yaml
  - nvidia-device-plugin.yaml
  # - postgres-operator.yaml
  - redpanda.yaml
  - sealed-secrets.yaml
  - zilla.yaml
