---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - cilium.yaml
  - sealed-secrets.yaml
  - grafana.yaml
  - nvidia-device-plugin.yaml
  - cloudflare.yaml
