---
apiVersion: v1
kind: ConfigMap
metadata:
  name: waterstream-config
data:
  KAFKA_BOOTSTRAP_SERVERS: "PLAINTEXT://redpanda:9092"
  MQTT_PORT: "1883"
  SESSION_TOPIC: "mqtt_sessions"
  RETAINED_MESSAGES_TOPIC: "mqtt_retained_messages"
  CONNECTION_TOPIC: "mqtt_connections"
  KAFKA_MESSAGES_DEFAULT_TOPIC: "mqtt_messages"
