---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waterstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waterstream
  template:
    metadata:
      labels:
        app: waterstream
    spec:
      containers:
        - name: waterstream
          image: simplematter/waterstream-kafka-arm64v8:latest
          envFrom:
            - configMapRef:
                name: waterstream
          volumeMounts:
            - name: license
              mountPath: /etc/waterstream.license
              readOnly: true
          resources: {}
      volumes:
        - name: license
          secret:
            secretName: waterstream
      hostNetwork: true
      securityContext:
        privileged: true
