---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - sealed-secret.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: waterstream-config
    envs:
      - .env
