---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - release.yaml
configMapGenerator:
  - name: postgres-operator-ui-values
    files:
      - values.yaml=values.yaml
components:
  - ../../../components/configurations
