apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: turingpicluster
spec:
  # https://github.com/k0sproject/k0sctl#host-fields
  hosts:
    - ssh:
        address: 192.168.4.78
        user: dudo
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: controller+worker
      installFlags:
        - --labels="tp2.turingpi.com/slot=1"
        - --disable-components=kube-proxy
    - ssh:
        address: 192.168.4.79
        user: dudo
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
      installFlags:
        - --labels="tp2.turingpi.com/slot=2"
    - ssh:
        address: 192.168.4.80
        user: dudo
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
      installFlags:
        - --labels="tp2.turingpi.com/slot=3"
    - ssh:
        address: 192.168.4.53
        user: dudo
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
      installFlags:
        - --labels="tp2.turingpi.com/slot=4"
  k0s:
    version: 1.29.2+k0s.0
    versionChannel: stable
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          provider: custom
          kubeProxy:
            disabled: true
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: false
