---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: notifications
spec:
  interval: 5m
  dependsOn:
    - name: secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./notifications/overlays/local
  prune: true
