---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
spec:
  interval: 5m
  dependsOn:
    - name: charts
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./secrets/overlays/local
  prune: true
