---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: slack-info
spec:
  summary: Kubernetes deployments
  providerRef:
    name: slack-info
  eventSeverity: info
  eventSources:
    - kind: ImageUpdateAutomation
      name: '*'
  exclusionList:
    - "waiting.*socket"
