---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sample-nginx
spec:
  interval: 10m
  url: https://github.com/sample/nginx
  ref:
    branch: main

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: sample-nginx
    namespace: flux-system
  path: ./deploy/overlays/local
  prune: true
  wait: true
  timeout: 5m
