---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  releaseName: sealed-secrets
  targetNamespace: kube-system
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      version: "^2.12.0"
  interval: 12h
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: sealed-secrets-values
