---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: flux-webhook
spec:
  parentRefs:
    - kind: Gateway
      name: http
      namespace: kube-system
  hostnames:
    - flux-webhook.dudo.dev
  rules:
    - backendRefs:
        - name: webhook-receiver
          port: 80
