# https://fluxcd.io/flux/guides/webhook-receivers/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - sealed-secret.yaml
  - http-route.yaml
  - receiver.yaml
