---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: flux-webhook
  namespace: flux-system
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: flux-webhook-token
  resources:
    - kind: GitRepository
      name: flux-system
    - kind: GitRepository
      name: sample-red
    - kind: GitRepository
      name: sample-blue
