---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flux-webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: TODO
  template:
    metadata:
      creationTimestamp: null
      name: flux-webhook-token
      namespace: flux-system
