---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  releaseName: metrics-server
  targetNamespace: kube-system
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      version: "^3.8.2"
  interval: 12h
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: metrics-server-values
