---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgres-operator
spec:
  releaseName: postgres-operator
  targetNamespace: postgres-operator
  chart:
    spec:
      chart: postgres-operator
      sourceRef:
        kind: HelmRepository
        name: postgres-operator
        namespace: flux-system
      version: "^1.10.0"
  interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: postgres-operator-values
