---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
spec:
  releaseName: tempo
  targetNamespace: grafana
  chart:
    spec:
      chart: tempo
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "1.14.0"
  interval: 1h
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: tempo-values
