---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redpanda-crds
spec:
  interval: 12h
  sourceRef:
    kind: GitRepository
    name: redpanda
    namespace: flux-system
  path: ./src/go/k8s/config/crd
  prune: true
