---
alertmanager:
  enabled: false

ingester:
  zoneAwareReplication:
    enabled: false

store_gateway:
  zoneAwareReplication:
    enabled: false

memcachedExporter:
  enabled: false

rollout_operator:
  enabled: false

nginx:
  enabled: false
gateway:
  enabledNonEnterprise: true

metaMonitoring:
  dashboards:
    enabled: true
  serviceMonitor:
    enabled: true
  grafanaAgent:
    enabled: true

minio:
  enabled: false
