# https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml
---
alertmanager:
  enabled: false

ingester:
  zoneAwareReplication:
    enabled: false

store_gateway:
  zoneAwareReplication:
    enabled: false

rollout_operator:
  enabled: false

nginx:
  enabled: false
gateway:
  enabledNonEnterprise: true

metaMonitoring:
  dashboards:
    enabled: true
  serviceMonitor:
    enabled: true
  grafanaAgent:
    enabled: true
