name: Update Flux

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # At 00:00 on Monday.

jobs:
  components:
    runs-on: ubuntu-latest
    env:
      BRANCH: update-flux
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
      - name: Check for updates
        id: update
        run: |
          flux install \
            --export > ./clusters/flux-system/gotk-components.yaml
          echo "flux_version=$(flux -v)" >> $GITHUB_OUTPUT
      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b $BRANCH
      - name: Commit
        run: |
          git add .
          git commit -am "Bump flux to ${{ steps.update.outputs.flux_version }}"
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --fill --head $BRANCH --label CD
